name = "Frendpack"
author = "Walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93af3088941c5daf976882d65dfcf616b3aafaf9364b02387bba56c8a8deafa3"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
